### ISSUE TITLE
Evaluation Dataset

### ISSUE THREAD

**Issue by mahi045** [lxing532/improve_topic_seg#1]
Could you please share the RULES and SECTION dataset (as mentioned in the paper) with me?

**Comment by beiweixiaoxu** [comment]
> Could you please share the RULES and SECTION dataset (as mentioned in the paper) with me?
https://github.com/sebastianarnold/WikiSection, wish help

**Comment by shaoyangxu** [comment]
> Could you please share the RULES and SECTION dataset (as mentioned in the paper) with me?

https://github.com/sebastianarnold/WikiSection, wish helpful
